@startuml
actor User
boundary Frontend
boundary Backend
database Database
entity Server
/' -------------- Innlogging ------------- '/
User -> Frontend: Log inn with \nusername + password
Frontend -> Backend: Username +\n password
Backend -> Database: Username +\n password
Database -> Backend: OK
Backend -> Frontend: OK
Frontend -> User: Now signed in

/' -------------- Spesielt for parkeringshus ------------- '/
User -> Frontend: Create P-house
Frontend -> Backend: Create P-house
Backend -> Frontend: All floors the same?
Frontend -> User: All floors the same?
User -> Frontend: Yes
Frontend -> Backend: Yes
Backend -> Frontend: How many floors?
Frontend -> User: How many floors?
User -> Frontend: X number of floors
Frontend -> Backend: X number of floors

/' -------------- Starter å lage ------------- '/
Backend -> Frontend: Fill inn data
Frontend -> User: Fill out this form
User -> Frontend: Filled out
Frontend -> Backend: Filled out
Backend -> Backend: Verify data
Backend -> Server: Upload picture
Backend -> Database: Insert data
Server -> Backend: Upload complete
Database -> Backend: Data inserted
Backend -> Frontend: Successfully done
Frontend -> User: P-house created successfully
@enduml
