@startuml
(*)  --> "Land on Home Page"
if "chose activity" then
-left->  "Adjust search filter"
--> "Scroll/read the parking-slot snippets"
-right-> "Book a parking slot"
else
--> "Register a parking slot"
endif

"Register a parking slot" -->  ===B1===
"Book a parking slot" --> ===B1===

===B1=== --> if "Logged in?"
 -->[No] if "Registerd?"
 -right->[No] "Register"
 --> "Login"
    else
    -->[Yes] "Login"
    endif
"Login" --> (*)
 else
 -right->[Yes] (*)


'--> "Register"
'
'--> "Register a parking slot"
'Endif
'-->"Login"

@enduml