@startuml
(*)  --> "Land on Home Page"
if "chose activity" then

-left->[Show available parking slots] "Adjust search filter"
--> "Scroll/read the parking-slot snippets"
-right-> "Book a parking slot"
else
-->[Register a parking slot] "Fill inn info"
endif

"Fill inn info" -->  ===B1===
"Book a parking slot" --> ===B1===

===B1=== --> if "Logged in?"
 -->[No] if "Registerd?"
 -right->[No] "Register"
 --> "Login"
    else
    -->[Yes] "Login"
    endif
"Login" --> Confirm
 else
 -right->[Yes] Confirm
 --> (*)

@enduml