@startuml
(*) --> Get users city
If "Users city registered" then
    --> [No] If "Users county registered" then
        --> [Yes] Select city
        --> [Selected city] Use selected city
    else
        --> [No] If "Users country registered" then
            --> [No] Select country
            --> [Country] Select county
        else
            --> [Yes] Select county
        endif
    endif
    --> [County] Select city
else
    --> [Yes] Use selected city
endif
If "Change city?" then
    --> [Yes] If "Change county?" then
        --> [Yes] If "Change country?" then
            --> [Yes] "Select new country"
            --> [New country] "Select new county"
        else
            --> [No] Select new county
            --> [New county] Select new city

        endif
    else
        --> [No] "Select new city"
        --> [New city] "Use city"
    endif
else
    --> [No] "Use city"
endif
-->(*)
@enduml